### PR TITLE
filter num errs by severity

### PR DESCRIPTION
**Pull request by ammkrn**
This is just a suggestion; right now the server output in VScode includes all messages in the number of errors it reports, including print/information statements, so something like `do-block.mm1` reports 22 "errors". Filter isn't an ExactSizeIterator, hence the fold.

### CODE REVIEW

**Comment by digama0** [comment]
I don't mind this, although the output is there only for testing / so that you can see that it's working. If you want a more informative breakdown we could bin the errors by type and report e.g. "4 errors, 2 infos"

**Comment by ammkrn** [comment]
That sounds good. `lsp-types` seems to provide four diagnostic levels. I'm not sure if you're already using or intend to use Warning and Hint, but `diagged <file>, 0 errors, 0 infos, 0 warnings, 0 hints` feels a bit crowded, so I think a nice default would be to always provide the number of errors while only showing the numbers for Info, Warning, and Hint when they're non-zero.
The `Write` methods implemented for `String` are infallible, so I just used unwrap to get the fmt results.

**Comment by digama0** [comment]
I was thinking to suppress '0' clauses (except perhaps error). Currently only error/warn/info are supported (both by the data structures and in actual practice). I don't know what "hint" is even supposed to mean. Have you seen it in use before?

**Comment by digama0** [comment]
To satisfy your curiosity re: warnings, they are generated when you omit the proof part for a `theorem` declaration in MM1 (which often happens when you populate an MM1 file from the corresponding MM0 file by just changing the extension). It's still basically an error, in the sense that you won't get a proof out the other end, but it makes you feel a bit better about yourself while doing so. I should set up `?`, the MM1 version of `sorry`, to also give a warning instead of an error. One advantage of having them be in a separate severity class is that you can suppress errors based on severity, which is nice when the file is full of unproven theorems that you aren't working on at the moment (for example [`x86.mm1`](https://github.com/digama0/mm0/blob/master/examples/x86.mm1) is full of unproven theorems, and I use `do (set-reporting 'warn #f)` to make it less noisy when I'm working on the file).

**Comment by ammkrn** [comment]
> I don't know what "hint" is even supposed to mean. Have you seen it in use before?

You might have seen them if you use Rust Analyzer; it's those small green ellipses you get for minor/style lints like not using shorthand struct initialization or putting a single import in brackets. They're less eye-catching, and vscode doesn't put them in the `problems` panel.

Thanks for the info about Warning; I think having a 'soft sorry' in `?`for WIP files is a really great idea. I just read the part about the `set-reporting` feature earlier tonight, that's very handy as well.

**Pull request merged**
